[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "snowpylot"
version = "1.0.6"
description = "A Python library for working CAAML.XML files from SnowPilot"
readme = "README.md"
authors = [
  { name="Mary Kate Connelly", email="connellymarykate@gmail.com" },
]
license = { file = "LICENSE" }
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
keywords = ["snowpit", "caaml", "snowpilot"]
requires-python = ">=3.7"

[project.urls]
"Homepage" = "https://github.com/connellymk/snowpylot"

[tool.bumpver]
current_version = "1.0.6"
version_pattern = "MAJOR.MINOR.PATCH"
commit_message = "bump version {old_version} -> {new_version}"
tag_message = "{new_version}"
tag_scope = "default"
pre_commit_hook = ""
post_commit_hook = ""
commit = true
tag = true
push = true

[tool.bumpver.file_patterns]
"pyproject.toml" = [
    'version = "(?P<major>[0-9]+)\\.(?P<minor>[0-9]+)\\.(?P<patch>[0-9]+)"',
    'current_version = "(?P<major>[0-9]+)\\.(?P<minor>[0-9]+)\\.(?P<patch>[0-9]+)"'
]
"README.md" = [
    'version = "(?P<major>[0-9]+)\\.(?P<minor>[0-9]+)\\.(?P<patch>[0-9]+)"'
]
"src/snowpylot/__init__.py" = [
    '__version__ = "(?P<major>[0-9]+)\\.(?P<minor>[0-9]+)\\.(?P<patch>[0-9]+)"'
]

#test